name: Ubuntu CI

on: [push, pull_request]

jobs:
  focal-ci:
    runs-on: ubuntu-latest
    name: Ubuntu Focal CI
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Compile and test
        id: ci
        uses: gazebo-tooling/action-gz-ci@focal
        with:
          codecov-enabled: true
          cpplint-enabled: true
          doxygen-enabled: true
      - name: Strip workspace prefix
        if: success() || failure() # always run even if the previous step fails
        run: |
          mkdir test_results/
          cp ./build/test_results/*.xml ./test_results/
          sed -i 's+/github/workspace/++g' ./test_results/*.xml
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure() # always run even if the previous step fails
        with:
          check_name: 'Ubuntu Focal Results'
          report_paths: 'build/test_results/*.xml'
  jammy-ci:
    runs-on: ubuntu-latest
    name: Ubuntu Jammy CI
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Compile and test
        id: ci
        uses: gazebo-tooling/action-gz-ci@jammy
      - name: Strip workspace prefix
        if: success() || failure() # always run even if the previous step fails
        run: |
          mkdir test_results/
          cp ./build/test_results/*.xml ./test_results/
          sed -i 's+/github/workspace/++g' ./test_results/*.xml
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure() # always run even if the previous step fails
        with:
          check_name: 'Ubuntu Jammy Results'
          report_paths: 'test_results/*.xml'
