name: PR Collection Labeler

on: pull_request

jobs:
  pr_collection_labeler:
    runs-on: ubuntu-latest
    steps:
    - name: Add collection labels
      if: github.event.action == 'opened'
      uses: gazebo-tooling/pr-collection-labeler@azeey/fix_addlabels
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
